# Generated by Django 3.1.7 on 2021-03-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_movieshots_rating_ratingstar_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Слоган'),
        ),
    ]
